<?php

// Custom Icon for Elementor

function bantec_icons($bantec_icons = array())
{

    $bantec_flaticon = array(
        'menu',
        'loupe',
        'placeholder',
        'envelope',
        'phone-call',
        'telephone-call',
        'mail',
        'location',
        'menu-1',
        'menu-2',
        'hamburger',
        'twitter',
        'hashtag',
        'right-up',
        'close',
        'check',
        'phone-call-1',
        'monitoring-software',
        'aggregate',
        'mobile-app',
        'consultant',
        'it',
        'satellite',
        'mobile-app-1',
        'it-service',
        'antenna',
        'cyber-security',
        'data-scientist',
        'quote',
        'technical-support',
        'assistant',
        'coding',
        'ux-design',
        'cyber-security-1',
        'desktop-pc',
        'machine-repair',
        'newspaper',
        'machine-repair-1',
        'laptop',
        'open-laptop',
        'imac-computer',
        'iphone',
        'macintosh',
        'instagram',
        'radio-tower',
        'good-feedback',
        'imac',
        'iphone-1',
        'mobile-data',
        'emoji',
        'incoming-message',
        'mobile-data-1',
        'mobile-phone',
        'online-security',
        'cloud-storage',
        'global-network',
        'web-research',
        'laptop-1',
        'computer-mouse',
        'mobile-phone-1',
        'satellite-signal',
        'video-call',
        'email',
        'next',
        'back',
        'plus',
        'remove',
        'down-arrow',
        'down-arrow-1',
        'down',
        'right-arrow',
        'right-arrow-1',
        'app-development',
        'growth',
        'solution',
        'idea',
        'creativity',
        'analytics',
        'monitor',
        'right',
        'delete',
        'check-1',
        'check-button',
        'check-2',
        'close-button',
        'software',
        'software-development',
        'management',
        'seo',
        'content-marketing',
    );

    $bantec_icons['bantec-icon_lists'] = array(
        'name' => 'bantec-icon_lists',
        'label' => esc_html__('Bantec - Premium', 'bantec-toolkit'),
        'labelIcon' => 'far fa-sun',
        'prefix' => 'flaticon-',
        'displayPrefix' => 'flaticon',
        'url' => BANTEC_ASSETS . 'elementor-addons/assets/font/flaticon_bantec.css',
        'icons' => $bantec_flaticon,
        'ver' => time(),
    );

    return $bantec_icons;
}

add_filter('elementor/icons_manager/additional_tabs', 'bantec_icons');
